export const projects = [
    {
        id: "1",
        title: "STRUDEL MUSIC SEQUENCER",
        github: "https://github.com/lokeshxh/Strudel-Music-Sequencer",
        demo: "https://strudel-music-sequencer.vercel.app/",
        techs: ["TypeScript", "React.js", "Strudel.js", "D3.js", "CSS", "Zustand"],
        duration: "3 weeks",
        roles: "Design / Frontend / Backend",
        summary: "A browser-based music sequencer built to explore the intersection of web technology and music production. Leveraging Strudel.js, React.js and Zustand, I developed a system that supports multi-instrument tracks with precise, per-note control over pitch and volume.",
        image1: "/sms_optimized.mp4",
        image2: "/sms2.webp",
        image3: "/sms3_optimized.mp4",
        image4: "/sms4.webp",
        bg1: "/black_bg.webp",
        bg2: "/sunset_bg.webp",
        bg3: "/cloth_bg.webp",
        bg4: "/concrete_bg.webp",
        next: "2",
    },
    {
        id: "2",
        title: "MENU SCANNER",
        github: "https://github.com/lokeshxh/Menu-Scanner",
        demo: null,
        techs: ["TypeScript", "Next.js", "Python", "Tailwind CSS", "FastAPI", "EasyOCR", "LibreTranslate API", "Pixabay API"],
        duration: "3 weeks",
        roles: "Design / Frontend / Backend",
        summary: "A web application that extracts text from menu images, translates it into the user's language, and retrieves representative dish images. Even if users can't read the original language, they can quickly grasp what each dish looks like and make more confident ordering decisions while traveling.",
        image1: "/ms_optimized.mp4",
        image2: "/ms2_optimized.mp4",
        image3: "/ms3.webp",
        image4: "/ms4_optimized.mp4",
        bg1: "/sea_bg.webp",
        bg2: "/flower_bg.webp",
        bg3: "/paper_bg.webp",
        bg4: "/concrete_bg.webp",
        next: "3"
    },
    {
        id: "3",
        title: "PORTFOLIO 1",
        github: null,
        demo: "https://lokesh.com",
        techs: ["WordPress", "CSS", "JavaScript", "Figma"],
        duration: "1 week",
        roles: "Design / Frontend",
        summary: "My first portfolio, built with WordPress, CSS, and JavaScript. This project marked my first exploration into web interactivity, featuring SVG animations and scroll-driven effects. It is a foundational milestone where I began blending technical logic with visual motion, setting the stage for my evolution into creative development.",
        image1: "/portfolio1_optimized.mp4",
        image2: "/portfolio2.webp",
        image3: "/portfolio3_optimized.mp4",
        image4: "/portfolio4_optimized.mp4",
        bg1: "/harbor_bg.webp",
        bg2: "/sea_bg.webp",
        bg3: "/stain_bg.webp",
        bg4: "/cloth_bg.webp",
        next: "1"
    }
] 